version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: watchup
      MARIADB_USER: watchuser
      MARIADB_PASSWORD: watchpassword
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./bd/schema:/docker-entrypoint-initdb.d
    networks:
      - monitor-net
    ports:
      - "3306:3306"


  central-server:
    build: ./Central
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mariadb
      - DB_NAME=watchup
      - DB_USER=watchuser
      - DB_PASSWORD=watchpassword
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mariadb
    networks:
      - monitor-net

  monitoring-agent:
    build: ./Agent
    volumes:
      - agent_credentials:/credentials # Volume para persistir a chave
    environment:
      - CENTRAL_SERVER_URL=http://central-server:5000
      - AGENT_NAME=agent-01
      - AGENT_ID=agent-01-id # ID fixo para o agente inicial
    depends_on:
      - central-server
    networks:
      - monitor-net

  webapp:
    build:
      context: ./Webapp
      dockerfile: setup_files/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./Webapp/Web:/var/www/html
    environment:
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mariadb
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge

volumes:
  mariadb_data:
  agent_credentials: