version: '3.8'

services:
  scylladb:
    image: scylladb/scylla:6.2.3
    command:
      - --developer-mode=1
      - --overprovisioned=1
      - --smp=2
      - --memory=2G
      - --api-address=0.0.0.0
    privileged: true
    volumes:
      - scylla_data:/var/lib/scylla
      - ./db/schema:/docker-entrypoint-initdb.d:ro
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 200000
        hard: 200000
    networks:
      - monitor-net
    ports:
      - "9042:9042"
      - "10000:10000"
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'DESCRIBE KEYSPACES'"]
      interval: 10s
      timeout: 20s
      retries: 15
      start_period: 120s
    environment:
      - SCYLLA_CLUSTER_NAME=MonitorCluster
      - SCYLLA_DATACENTER=dc1
    # Novo comando para executar o script após inicialização
    entrypoint: |
      bash -c '
      /docker-entrypoint.py &&
      cqlsh -f /init-scripts/init.cql &&
      tail -f /dev/null
      '


  central-server:
    build: ./Central
    ports:
      - "5000:5000"
    environment:
      - SCYLLA_HOSTS=scylladb
      - SCYLLA_KEYSPACE=watchup
    depends_on:
      scylladb:
        condition: service_healthy
    networks:
      - monitor-net



  monitoring-agent:
    build: ./Agent
    environment:
      - CENTRAL_SERVER_URL=http://central-server:5000
      - AGENT_NAME=agent-01
      - CHECK_INTERVAL=30
    ports:  # Adicione esta seção
      - "5001:5001"
    networks:
      - monitor-net
    logging:  # Adicione para debug
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  webapp:
    build:
      context: ./Webapp  # Contexto principal agora é a pasta Webapp
      dockerfile: setup_files/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./Webapp/Web:/var/www/html  # Adicione este volume para desenvolvimento
    networks:
      - monitor-net
    depends_on:
      - scylladb
    environment:
      - SCYLLA_HOSTS=scylladb
      - SCYLLA_KEYSPACE=watchup
      
networks:
  monitor-net:
    driver: bridge

volumes:
  scylla_data: