# Kubernetes Manifests para a Aplicação WatchUP (COM SENHAS HARCODED)

# --- PersistentVolumeClaim para os dados do MariaDB ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

# --- ADICIONADO: PVC para as credenciais do agente ---
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-credentials-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi # Um tamanho pequeno é suficiente

---
# --- ConfigMap para o script de inicialização do MariaDB ---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-init-scripts
# O Jenkinsfile popula este ConfigMap com os dados do init.sql.

---
# --- MariaDB Deployment ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:latest # Imagem pública do Docker Hub
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: "rootpassword"
            - name: MARIADB_DATABASE
              value: "watchup"
            - name: MARIADB_USER
              value: "watchuser"
            - name: MARIADB_PASSWORD
              value: "watchpassword"
          volumeMounts:
            - name: mariadb-persistent-storage
              mountPath: /var/lib/mysql
            - name: mariadb-initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mariadb-persistent-storage
          persistentVolumeClaim:
            claimName: mariadb-data-pvc
        - name: mariadb-initdb
          configMap:
            name: mariadb-init-scripts

---
# --- MariaDB Service (Apenas interno) ---
apiVersion: v1
kind: Service
metadata:
  name: mariadb # Nome DNS interno para o serviço
spec:
  selector:
    app: mariadb
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP # Acessível apenas dentro do cluster

---
# --- Central Server Deployment ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-server
  labels:
    app: central-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: central-server
  template:
    metadata:
      labels:
        app: central-server
    spec:
      containers:
        - name: central-server
          image: central-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "mariadb"
            - name: DB_NAME
              value: "watchup"
            - name: DB_USER
              value: "watchuser"
            - name: DB_PASSWORD
              value: "watchpassword"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
---
# --- Central Server Service (Externo) ---
apiVersion: v1
kind: Service
metadata:
  name: central-server
spec:
  selector:
    app: central-server
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer

---
# --- Monitoring Agent Deployment ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-agent
  labels:
    app: monitoring-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-agent
  template:
    metadata:
      labels:
        app: monitoring-agent
    spec:
      securityContext:
        sysctls:
          - name: net.ipv4.ip_local_port_range
            value: "1024 65535"
      containers:
        - name: monitoring-agent
          image: monitoring-agent:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: CENTRAL_SERVER_URL
              value: "http://central-server:5000"
            - name: AGENT_NAME
              value: "agent-01"
            # --- ADICIONADO: AGENT_ID que estava faltando ---
            - name: AGENT_ID
              value: "agent-01-id"
            - name: CHECK_INTERVAL
              value: "30"
          # --- ADICIONADO: Montagem do volume de credenciais ---
          volumeMounts:
            - name: agent-credentials-storage
              mountPath: /credentials
      # --- ADICIONADO: Definição do volume que usa o PVC ---
      volumes:
        - name: agent-credentials-storage
          persistentVolumeClaim:
            claimName: agent-credentials-pvc
---
# --- Webapp Deployment ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: webapp:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
---
# --- Webapp Service (MODIFICADO para ClusterIP) ---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    app: webapp
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP

---
# --- Ingress para a Webapp (NOVO RECURSO) ---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webapp
            port:
              number: 80